config/routes.rb
Rails.application.routes.draw do
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  # 管理者側のルーティング設定
  namespace :admin do
    root to: 'homes#top'
    resources :customers, only:[:index, :show, :edit, :update] do
      member do
        get :followers, :followeds
      end
    end
    resources :posts, only: [:index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search"
  end
  
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    get 'about',to: 'homes#about'
    resources :posts, only: [:index, :new, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :customers, only:[:show, :edit, :update] do
      member do
        get :confirm
        patch :withdraw 
        get :followers, :followeds
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
    end
    resources :notifications, only: [:index, :destroy]
    get "search" => "searches#search"
    
  end  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  enum is_deleted: { exist: false, withdraw: true }
  
  has_one_attached :profile_image
  
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :view_counts, dependent: :destroy
  
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :following_customers, through: :followers, source: :followed
  has_many :follower_customers, through: :followeds, source: :follower
  
  has_many :notifications, dependent: :destroy

  validates :name, :email, presence: true
  validates :introduction, length: { maximum: 200 }
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.name = 'ゲストユーザー'
      customer.password = SecureRandom.urlsafe_base64
    end
  end
  
  def guest_user?
    email == 'guest@example.com'
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  # フォローしたときの処理
  def follow(customer_id)
    followers.create(followed_id: customer_id)
  end
  # フォローを外すときの処理
  def unfollow(customer_id)
    followers.find_by(followed_id: customer_id).destroy
  end
  # フォローしているか判定
  def following?(customer)
    following_customers.include?(customer)
  end
  
  def self.ransackable_attributes(auth_object = nil)
    [ "name"]
  end
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!


  def index
    @customers = Customer.page(params[:page]).per(30)
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts.order(created_at: :desc)
    @following_customers = @customer.following_customers
    @follower_customers = @customer.follower_customers
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path
      flash[:notice] = "更新が完了しました"
    else
      flash[:alert] = "ユーザー情報を更新できませんでした"
      render :edit
    end
  end
  
  def followeds
    @customer = Customer.find(params[:id])
    @customers = @customer.following_customers
  end
  
  def followers
    @customer = Customer.find(params[:id])
    @customers = @customer.follower_customers
  end

   private

  def customer_params
    params.require(:customer).permit(:name, :introduction, :email, :profile_image, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <h4><strong>プロフィール編集</strong></h4>
      <%= form_with model: @customer, url:admin_customer_path, metod: :patch, local: true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :profile_image, "プロフィール画像" %>
        <%= f.file_field :profile_image, class: "form-control-file profile_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction, "自己紹介" %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <td>ステータス</td>
        <td>
      　   <%= f.radio_button :is_deleted, Customer.is_deleteds.key(false) %>
          <%= f.label :is_deleted_exist, Customer.is_deleteds_i18n[:exist] %>
          <%= f.radio_button :is_deleted, Customer.is_deleteds.key(true) %>
          <%= f.label :is_deleted_withdraw, Customer.is_deleteds_i18n[:withdraw] %>
        </td>
      </div>
      <div class="form-group">
        <%= f.submit "更新する", class: 'btn btn-outline-secondary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/followeds.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <% if @customer.following_customers.present? %>
        <h5><strong>フォロー中</strong></h5>
        <table class ="table">
          <% @customer.following_customers.each do |customer| %>  
          <tr align="center">
            <td><%= image_tag customer.get_profile_image(50, 50), class:"rounded-circle"; %></td>
            <td><%= link_to customer.name, admin_customer_path(customer), class: "text-black-50" %></td>
            <td>
              <%= link_to followeds_admin_customer_path(customer), class: "text-black-50" do %>
                <h6><strong><%= customer.followers.count %></strong> フォロー</h6>
              <% end %>
            </td>
            <td>
              <%= link_to followers_admin_customer_path(customer), class: "text-black-50" do %>
                <h6><strong><%= customer.followeds.count %></strong> フォロワー</h6>
              <% end %>
            </td>
          <% end %>
          </tr>
        </table>
      <% else %>
        <h5><strong>フォローしているユーザーはいません</strong></h5>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/followers.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <% if @customer.follower_customers.present? %>
        <h5><strong>フォロワー</strong></h5>
        <table class ="table">
          <% @customer.follower_customers.each do |customer| %>  
          <tr align="center">
            <td><%= image_tag customer.get_profile_image(50, 50), class:"rounded-circle"; %></td>
            <td><%= link_to customer.name, admin_customer_path(customer), class: "text-black-50" %></td>
            <td>
              <%= link_to followeds_admin_customer_path(customer), class: "text-black-50" do %>
                <h6><strong><%= customer.followers.count %></strong> フォロー</h6>
              <% end %>
            </td>
            <td>
              <%= link_to followers_admin_customer_path(customer), class: "text-black-50" do %>
                <h6><strong><%= customer.followeds.count %></strong> フォロワー</h6>
              <% end %>
            </td>
          <% end %>
          </tr>
        </table>
      <% else %>
        <h5><strong>フォローされているユーザーはいません</strong></h5>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <h5><strong>ユーザー一覧</strong></h5>
      <table class ="table">
        <tr align="center">
          <td>ユーザーID</td>
          <td></td>
          <td>ユーザー名</td>
          <td>メールアドレス</td>
          <td>ステータス</td>
        </tr>
        <% @customers.each do |customer| %>
        <tr align="center">
          <td><%= customer.id %></td>
          <td><%= image_tag customer.get_profile_image(50, 50), class:"rounded-circle"; %></td>
          <td><%= link_to customer.name, admin_customer_path(customer), class: "text-black-50" %></td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_deleted == "exist" %>
              <p style = "color: #4ec51e;">有効</p>
            <% else %>
              <p style = "color: #ff3838;">退会</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
      <div>
        <%= paginate @customers %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container py-4">
  <div class="row">
    <div class="col-md-7 order-md-2">
      <h5><%= @customer.name %></h5>
      <p><%= @customer.introduction %></p>
    </div>
    <div class="col-md-3 order-md-1">
      <%= image_tag @customer.get_profile_image(120,120), class:"rounded-circle"; %>
    </div>
  </div>
  
  <div class="row py-3">
    <div class="col-md-7 order-md-2">
      <h6><%= link_to followeds_admin_customer_path(@customer), class: "text-black-50" do %>
        <strong><%= @customer.followers.count %></strong> フォロー
        <% end %>
      </h6>
      <h6><%= link_to followers_admin_customer_path(@customer), class: "text-black-50" do %>
        <strong><%= @customer.followeds.count %></strong> フォロワー
        <% end %>
      </h6>  
    </div>
    <div class="col-md-3 order-md-1">
      <p><%= link_to "プロフィール編集", edit_admin_customer_path(@customer), class:"btn btn-outline-secondary" %></p>
    </div>
  </div>
</div>

<hr>

<div class="container marketing">
  <div class="row">
  <% @posts.each do |post| %>
    <div class="col-lg-4">
      <p><%= image_tag post.get_image(80,80), class:"rounded-circle"; %></p>
      <h5><strong><%= post.post_name %></strong></h5>
      <p class="small text-black-50"><i class="fas fa-user"></i> <%= @customer.name %></p>
      <p class="small text-black-50"><i class="fas fa-heart"></i> <%= post.favorites.count %></p>
      <p><%= link_to "詳細を見る", admin_post_path(post), class:"btn btn-outline-secondary" %></p>
    </div>
  <% end %>
  </div>
</div>