config/routes.rb
Rails.application.routes.draw do
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  # 管理者側のルーティング設定
  namespace :admin do
    root to: 'homes#top'
    resources :customers, only:[:index, :show, :edit, :update] do
      member do
        get :followers, :followeds
      end
    end
    resources :posts, only: [:index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search"
  end
  
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    get 'about',to: 'homes#about'
    resources :posts, only: [:index, :new, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :customers, only:[:show, :edit, :update] do
      member do
        get :confirm
        patch :withdraw 
        get :followers, :followeds
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
    end
    resources :notifications, only: [:index, :destroy]
    get "search" => "searches#search"
    
  end  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/search.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <% search_word = @q %>
      <% if @post.present? || @customer.present? %>
      <table class ="table">
        <h5><strong>検索結果 "<%= search_word %>"</strong></h5>
        <% if @post.present? %>
          <% @post.each do |post| %>
          <tr align="center">
            <td><%= image_tag post.get_image(50, 50), class:"rounded-circle"; %></td>
            <td><%= post.post_name %></td>
            <td class="small text-black-50"><i class="fas fa-user"></i> <%= post.customer.name %></td>
            <td class="small text-black-50"><i class="fas fa-heart"></i> <%= post.favorites.count %></td>
            <td><%= link_to "詳細を見る", admin_post_path(post), class:"btn btn-outline-secondary" %></td>
          </tr>
          <% end %>
        <% end %>
        <% if @customer.present? %>
          <% @customer.each do |customer| %>  
          <tr align="center">
            <td><%= image_tag customer.get_profile_image(50, 50), class:"rounded-circle"; %></td>
            <td><%= link_to customer.name, admin_customer_path(customer), class: "text-black-50" %></td>
            <td>
              <%= link_to followeds_admin_customer_path(customer), class: "text-black-50" do %>
                <h6><strong><%= customer.followers.count %></strong> フォロー</h6>
              <% end %>
            </td>
            <td>
              <%= link_to followers_admin_customer_path(customer), class: "text-black-50" do %>
                <h6><strong><%= customer.followeds.count %></strong> フォロワー</h6>
              <% end %>
            </td>
            
          <% end %>
          </tr>
        <% end %>
      <% else %>
        <h5><strong>検索結果がありません</strong></h5>
      <% end %>
      </table>
    </div>
  </div>
</div>