config/routes.rb
Rails.application.routes.draw do
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  # 管理者側のルーティング設定
  namespace :admin do
    root to: 'homes#top'
    resources :customers, only:[:index, :show, :edit, :update] do
      member do
        get :followers, :followeds
      end
    end
    resources :posts, only: [:index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search"
  end
  
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    get 'about',to: 'homes#about'
    resources :posts, only: [:index, :new, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :customers, only:[:show, :edit, :update] do
      member do
        get :confirm
        patch :withdraw 
        get :followers, :followeds
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
    end
    resources :notifications, only: [:index, :destroy]
    get "search" => "searches#search"
    
  end  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :customer
  belongs_to :post
  
  validates :comment, presence: true
  
  has_one :notification, as: :subject, dependent: :destroy
  
  after_create_commit :create_notifications
  
   private
   
  def create_notifications
    Notification.create(subject: self, customer: self.post.customer, action_type: :commented_to_own_post)
  end
  
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  
  def destroy
    @post_comment = PostComment.find(params[:id]).destroy
    @post_comment.destroy
    @post = Post.find(params[:post_id])
  end
  
   private
  
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
  
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/_index.html.erb
<table class ="table">
  <tbody>
    <% post.post_comments.each do |post_comment| %>
    <tr>
      <td width = "18%">
        <%= link_to admin_customer_path(post_comment.customer) do %>
          <%= image_tag post_comment.customer.get_profile_image(36,36), class:"rounded-circle"; %><br>
          <p class="small text-black-50"><%= post_comment.customer.name %></p>
        <% end %>
      </td>
      <td width = "69%"><%= post_comment.comment %></td>
      <td>
        <%= link_to "削除", admin_post_post_comment_path(post, post_comment), method: :delete, remote: true, class: "btn btn-outline-danger btn-sm" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/post_comments/destroy.js.erb
$('#admin-post-comments').html("<%= j(render "admin/post_comments/index", post: @post) %>");
$('#comment_count').html("<%= @post.post_comments.count %>")