config/routes.rb
Rails.application.routes.draw do
  
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  # 管理者側のルーティング設定
  namespace :admin do
    root to: 'homes#top'
    resources :customers, only:[:index, :show, :edit, :update] do
      member do
        get :followers, :followeds
      end
    end
    resources :posts, only: [:index, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search"
  end
  
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  # 会員側のルーティング設定
  scope module: :public do
    root to: 'homes#top'
    get 'about',to: 'homes#about'
    resources :posts, only: [:index, :new, :show, :edit, :create, :destroy, :update] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :customers, only:[:show, :edit, :update] do
      member do
        get :confirm
        patch :withdraw 
        get :followers, :followeds
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
    end
    resources :notifications, only: [:index, :destroy]
    get "search" => "searches#search"
    
  end  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-4">
      <%= link_to root_path do %>
        <%= image_tag 'Nutrin.png', size: '90x45' %>
      <% end %>
      <p class="small text-black-50">栄養バランスを考えたレシピの<br>
      情報共有コミュニティ</p>
    </div>
    <div class="col-md-8">
      <h6 class="mt-1">About</h6>
      <ul class="p-0 list-unstyled">
        <li>
          <%= link_to about_path, class: "small text-black-50" do %>
            Nutrinについて
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <div class="navbar navbar-brand">
      <% if admin_signed_in? %>
        <%= link_to admin_posts_path do %>
          <%= image_tag 'Nutrin.png', size: '90x45' %>
        <% end %>
      <% else %>
        <%= link_to root_path do %>
          <%= image_tag 'Nutrin.png', size: '90x45' %>
        <% end %>
      <% end %>
    </div>
    <% if customer_signed_in? %>
    <!-- 検索機能 -->
    <div class="row">
      <%= form_with url: search_path, local: true, method: :get do |f| %>
        <%= f.text_field :q, required: true, class: "form-control d-inline-block w-auto", type: "search", placeholder: "検索", aria_label: "検索" %>
        <button class="btn btn-outline-success" type="submit">
          <i class="fa-solid fa-magnifying-glass"></i>
        </button>
      <% end %>
    </div>
    <% end %>
    <% if admin_signed_in? %>
    <!-- 検索機能 -->
    <div class="row">
      <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
        <%= f.text_field :q, required: true, class: "form-control d-inline-block w-auto", type: "search", placeholder: "検索", aria_label: "検索" %>
        <button class="btn btn-outline-success" type="submit">
          <i class="fa-solid fa-magnifying-glass"></i>
        </button>
      <% end %>
    </div>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <!--管理者のログイン時-->
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to admin_posts_path, class: "nav-link mt-3 small" do %>
            <i class="fas fa-coffee"></i>
              投稿一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_customers_path, class: "nav-link mt-3 small" do %>
            <i class="fas fa-user-friends"></i>
              ユーザ一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link mt-3 small" do %>
            <i class="fas fa-sign-out-alt"></i>
              ログアウト
            <% end %>
          </li>
        <!--ユーザーのログイン時-->
        <% elsif customer_signed_in? %>
          <li class="nav-item">
            <%= link_to posts_path, class: "nav-link mt-3 small" do %>
            <i class="fa-solid fa-house-chimney"></i>
              タイムライン
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to notifications_path, class: "nav-link mt-3 small" do %>
            <% if current_customer && current_customer.notifications.where(checked: false).exists? %>
            <i class="fa-sharp fa-solid fa-bell fa-beat" style="color: #f2ee7d;"></i>
            <% else %>
            <i class="fa-sharp fa-solid fa-bell"></i>
            <% end %>
              通知
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_post_path, class: "nav-link mt-3 small" do %>
            <i class="fas fa-pencil"></i>
              投稿する
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to customer_path(current_customer), class: "nav-link mt-3 small" do %>
            <i class="fas fa-user-cog"></i>
              マイページ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link mt-3 small" do %>
            <i class="fas fa-sign-out-alt"></i>
              ログアウト
            <% end %>
          </li>
        <!--ログイン前画面-->
        <% else %>
          <li class="nav-item">
            <%= link_to new_customer_registration_path, class: "nav-link mt-3 small" do %>
            <i class="fas fa-user-edit"></i>
              新規登録
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_customer_session_path, class: "nav-link mt-3 small" do %>
            <i class="fas fa-sign-in-alt"></i>
              ログイン
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to customers_guest_sign_in_path, class: "nav-link mt-3 small", method: :post  do %>
            <i class="fa-solid fa-users"></i>
              ゲストログイン
            <% end %>
          </li>
        <% end %>
      </ul>
    </div> 
  </div>  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nutrin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.png') %>
    <script src="https://kit.fontawesome.com/5800f3fb2b.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <%= render 'layouts/header' %>
    </header>
    <main class="mb-auto">
      <% if flash[:notice] %>
        <p class="alert alert-primary"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert alert-danger"><%= flash.now[:alert] %></p>
      <% end %>
      <%= yield %>
    </main>
    <footer class="pt-3 pb-2 shadow-lg">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>